# Generated by Django 5.0.6 on 2024-05-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilemanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cummulative_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='highest_score',
            field=models.IntegerField(default=0),
        ),
    ]
